variable "project_id" {}
variable "project_region" {}
variable "vpc_name" {}
variable "route_mode" {}
variable "ip_cidr_range" {}
variable "custom_subnet" {}
variable "vpc_description" {}
variable "subnet_description" {}
variable "aggregation_interval" {}
variable "flow_logs_metadata" {}
variable "allow_access_specific_ip" {}
variable "protocol" {}
variable "ports" {}
variable "source_ranges" {}
variable "compute_instance_name" {}
variable "compute_instance_description" {}
variable "compute_instance_label" {}
variable "machine_type" {}
variable "source_image" {}